CREATE TABLE zonesv (
  ID int PRIMARY KEY,
  ZoneName varchar(15) NOT NULL
);


INSERT INTO zonesv (ID, ZoneName) VALUES (1, 'Occidental');
INSERT INTO zonesv (ID, ZoneName) VALUES (2, 'Central');
INSERT INTO zonesv (ID, ZoneName) VALUES (3, 'Paracentral');
INSERT INTO zonesv (ID, ZoneName) VALUES (4, 'Oriental');
	
CREATE TABLE depsv (
  ID int PRIMARY KEY,
  DepName varchar(30) NOT NULL,
  ISOCode char(5) NOT NULL,
  ZONESV_ID int NOT NULL
);
ALTER TABLE depsv ADD FOREIGN KEY (ZONESV_ID) REFERENCES zonesv (ID);


INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (1, 'Ahuachapan', 'SV-AH', 1);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES 	(2, 'Santa Ana', 'SV-SA', 1);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES 	(3, 'Sonsonate', 'SV-SO', 1);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (4, 'La Libertad', 'SV-CH', 2);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (5, 'Chalatenango', 'SV-CH', 2);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (6, 'San Salvador', 'SV-SS', 2);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (7, 'Cuscatlan', 'SV-CU', 3);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (8, 'La Paz', 'SV-PA', 3);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (9, 'Cabanas', 'SV-CA', 3);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (10, 'San Vicente', 'SV-SV', 3);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (11, 'Usulutan', 'SV-US', 4);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (12, 'Morazan', 'SV-MO', 4);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (13, 'San Miguel', 'SV-SM', 4);
INSERT INTO depsv (ID, DepName, ISOCode, ZONESV_ID) VALUES (14, 'La Union', 'SV-UN', 4);




CREATE TABLE munsv (
  ID int PRIMARY KEY,
  MunName varchar(100) NOT NULL ,
  DEPSV_ID int NOT NULL 
);
ALTER TABLE munsv ADD FOREIGN KEY (DEPSV_ID) REFERENCES depsv (ID);

INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(1, 'Ahuachapan', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(2, 'Jujutla', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(3, 'Atiquizaya', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(4, 'Concepci�n de Ataco', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(5, 'El Refugio', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(6, 'Guaymango', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(7, 'Apaneca', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(8, 'San Francisco Men�ndez', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(9, 'San Lorenzo', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(10, 'San Pedro Puxtla', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(11, 'Tacuba', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(12, 'Turin', 1);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(13, 'Candelaria de la Frontera', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(14, 'Chalchuapa', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(15, 'Coatepeque', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(16, 'El Congo', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(17, 'El Porvenir', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(18, 'Masahuat', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(19, 'Metap�n', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(20, 'San Antonio Pajonal', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(21, 'San Sebasti�n Salitrillo', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(22, 'Santa Ana', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(23, 'Santa Rosa Guachipil�n', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(24, 'Santiago de la Frontera', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(25, 'Texistepeque', 2);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(26, 'Acajutla', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(27, 'Armenia', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(28, 'Caluco', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(29, 'Cuisnahuat', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(30, 'Izalco', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(31, 'Juay�a', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(32, 'Nahuizalco', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(33, 'Nahulingo', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(34, 'Salcoatit�n', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(35, 'San Antonio del Monte', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(36, 'San Juli�n', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(37, 'Santa Catarina Masahuat', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(38, 'Santa Isabel Ishuat�n', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(39, 'Santo Domingo de Guzm�n', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(40, 'Sonsonate', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(41, 'Sonzacate', 3);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(42, 'Alegr�a', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(43, 'Berl�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(44, 'California', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(45, 'Concepci�n Batres', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(46, 'El Triunfo', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(47, 'Ereguayqu�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(48, 'Estanzuelas', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(49, 'Jiquilisco', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(50, 'Jucuapa', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(51, 'Jucuar�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(52, 'Mercedes Uma�a', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(53, 'Nueva Granada', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(54, 'Ozatl�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(55, 'Puerto El Triunfo', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(56, 'San Agust�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(57, 'San Buenaventura', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(58, 'San Dionisio', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(59, 'San Francisco Javier', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(60, 'Santa Elena', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(61, 'Santa Mar�a', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(62, 'Santiago de Mar�a', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(63, 'Tecap�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(64, 'Usulut�n', 11);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(65, 'Carolina', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(66, 'Chapeltique', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(67, 'Chinameca', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(68, 'Chirilagua', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(69, 'Ciudad Barrios', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(70, 'Comacar�n', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(71, 'El Tr�nsito', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(72, 'Lolotique', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(73, 'Moncagua', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(74, 'Nueva Guadalupe', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(75, 'Nuevo Ed�n de San Juan', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(76, 'Quelepa', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(77, 'San Antonio del Mosco', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(78, 'San Gerardo', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(79, 'San Jorge', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(80, 'San Luis de la Reina', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(81, 'San Miguel', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(82, 'San Rafael Oriente', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(83, 'Sesori', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(84, 'Uluazapa', 13);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(85, 'Arambala', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(86, 'Cacaopera', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(87, 'Chilanga', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(88, 'Corinto', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(89, 'Delicias de Concepci�n', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(90, 'El Divisadero', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(91, 'El Rosario (Moraz�n)', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(92, 'Gualococti', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(93, 'Guatajiagua', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(94, 'Joateca', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(95, 'Jocoaitique', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(96, 'Jocoro', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(97, 'Lolotiquillo', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(98, 'Meanguera', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(99, 'Osicala', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(100, 'Perqu�n', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(101, 'San Carlos', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(102, 'San Fernando (Moraz�n)', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(103, 'San Francisco Gotera', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(104, 'San Isidro (Moraz�n)', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(105, 'San Sim�n', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(106, 'Sensembra', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(107, 'Sociedad', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(108, 'Torola', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(109, 'Yamabal', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(110, 'Yoloaiqu�n', 12);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(111, 'La Uni�n', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(112, 'San Alejo', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(113, 'Yucuaiqu�n', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(114, 'Conchagua', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(115, 'Intipuc�', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(116, 'San Jos�', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(117, 'El Carmen (La Uni�n)', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(118, 'Yayantique', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(119, 'Bol�var', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(120, 'Meanguera del Golfo', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(121, 'Santa Rosa de Lima', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(122, 'Pasaquina', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(123, 'Anamoros', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(124, 'Nueva Esparta', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(125, 'El Sauce', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(126, 'Concepci�n de Oriente', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(127, 'Polor�s', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(128, 'Lislique', 14);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(129, 'Antiguo Cuscatl�n', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(130, 'Chiltiup�n', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(131, 'Ciudad Arce', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(132, 'Col�n', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(133, 'Comasagua', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(134, 'Huiz�car', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(135, 'Jayaque', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(136, 'Jicalapa', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(137, 'La Libertad', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(138, 'Santa Tecla', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(139, 'Nuevo Cuscatl�n', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(140, 'San Juan Opico', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(141, 'Quezaltepeque', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(142, 'Sacacoyo', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(143, 'San Jos� Villanueva', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(144, 'San Mat�as', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(145, 'San Pablo Tacachico', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(146, 'Talnique', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(147, 'Tamanique', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(148, 'Teotepeque', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(149, 'Tepecoyo', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(150, 'Zaragoza', 4);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(151, 'Agua Caliente', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(152, 'Arcatao', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(153, 'Azacualpa', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(154, 'Cancasque', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(155, 'Chalatenango', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(156, 'Cital�', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(157, 'Comapala', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(158, 'Concepci�n Quezaltepeque', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(159, 'Dulce Nombre de Mar�a', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(160, 'El Carrizal', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(161, 'El Para�so', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(162, 'La Laguna', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(163, 'La Palma', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(164, 'La Reina', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(165, 'Las Vueltas', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(166, 'Nueva Concepci�n', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(167, 'Nueva Trinidad', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(168, 'Nombre de Jes�s', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(169, 'Ojos de Agua', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(170, 'Potonico', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(171, 'San Antonio de la Cruz', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(172, 'San Antonio Los Ranchos', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(173, 'San Fernando (Chalatenango)', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(174, 'San Francisco Lempa', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(175, 'San Francisco Moraz�n', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(176, 'San Ignacio', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(177, 'San Isidro Labrador', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(178, 'Las Flores', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(179, 'San Luis del Carmen', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(180, 'San Miguel de Mercedes', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(181, 'San Rafael', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(182, 'Santa Rita', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(183, 'Tejutla', 5);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(184, 'Cojutepeque', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(185, 'Candelaria', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(186, 'El Carmen (Cuscatl�n)', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(187, 'El Rosario (Cuscatl�n)', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(188, 'Monte San Juan', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(189, 'Oratorio de Concepci�n', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(190, 'San Bartolom� Perulap�a', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(191, 'San Crist�bal', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(192, 'San Jos� Guayabal', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(193, 'San Pedro Perulap�n', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(194, 'San Rafael Cedros', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(195, 'San Ram�n', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(196, 'Santa Cruz Analquito', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(197, 'Santa Cruz Michapa', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(198, 'Suchitoto', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(199, 'Tenancingo', 7);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(200, 'Aguilares', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(201, 'Apopa', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(202, 'Ayutuxtepeque', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(203, 'Cuscatancingo', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(204, 'Ciudad Delgado', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(205, 'El Paisnal', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(206, 'Guazapa', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(207, 'Ilopango', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(208, 'Mejicanos', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(209, 'Nejapa', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(210, 'Panchimalco', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(211, 'Rosario de Mora', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(212, 'San Marcos', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(213, 'San Mart�n', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(214, 'San Salvador', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(215, 'Santiago Texacuangos', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(216, 'Santo Tom�s', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(217, 'Soyapango', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(218, 'Tonacatepeque', 6);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(219, 'Zacatecoluca', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(220, 'Cuyultit�n', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(221, 'El Rosario (La Paz)', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(222, 'Jerusal�n', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(223, 'Mercedes La Ceiba', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(224, 'Olocuilta', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(225, 'Para�so de Osorio', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(226, 'San Antonio Masahuat', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(227, 'San Emigdio', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(228, 'San Francisco Chinameca', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(229, 'San Pedro Masahuat', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(230, 'San Juan Nonualco', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(231, 'San Juan Talpa', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(232, 'San Juan Tepezontes', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(233, 'San Luis La Herradura', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(234, 'San Luis Talpa', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(235, 'San Miguel Tepezontes', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(236, 'San Pedro Nonualco', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(237, 'San Rafael Obrajuelo', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(238, 'Santa Mar�a Ostuma', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(239, 'Santiago Nonualco', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(240, 'Tapalhuaca', 8);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(241, 'Cinquera', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(242, 'Dolores', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(243, 'Guacotecti', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(244, 'Ilobasco', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(245, 'Jutiapa', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(246, 'San Isidro (Caba�as)', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(247, 'Sensuntepeque', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(248, 'Tejutepeque', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(249, 'Victoria', 9);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(250, 'Apastepeque', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(251, 'Guadalupe', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(252, 'San Cayetano Istepeque', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(253, 'San Esteban Catarina', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(254, 'San Ildefonso', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(255, 'San Lorenzo', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(256, 'San Sebasti�n', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(257, 'San Vicente', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(258, 'Santa Clara', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(259, 'Santo Domingo', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(260, 'Tecoluca', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(261, 'Tepetit�n', 10);
INSERT INTO munsv (ID, MunName, DEPSV_ID) VALUES(262, 'Verapaz', 10);
